function [opt] = mvpa_chooseMask(opt)

opt.maskName = [];

for iSub = 1:numel(opt.subjects)

    subID = opt.subjects{iSub};

    % default one is the old way
    if isempty(opt.roiMethod)
        opt.roiMethod = 'atlases';
    end

    % different subfolders for different methods
    %         opt.maskPath = fullfile(opt.dir.rois, opt.roiMethod);

    % go to maskPath and get all the .nii files


    % based on the method we're using, pick the ROIs
    switch opt.roiMethod
        case 'atlases' % get neurosynth threshold 7
            atlas_filename = [opt.dir.rois, '/sub-',num2str(subID),'/rsub-',num2str(subID),'_hemi-*_space-MNI_atlas-*.nii'];
            atlas_files = dir(atlas_filename);
            opt.maskName = horzcat(opt.maskName, {atlas_files.name});

        case 'general_coords_10mm'
            opt.maskName = horzcat(opt.maskName, ...
                { ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-NeurosynthCoords_label-VWFAfr_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-NeurosynthCoords_label-lLO_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-NeurosynthCoords_label-rLO_radius-10mm_mask.nii'), ...
                });

        case 'individual_coords_marsbar'
            opt.maskName = horzcat(opt.maskName, ...
                { ...
                strcat('rsub-', num2str(subID), '_space-MNI_label-VWFAfr_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_label-lLO_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_label-rLO_radius-10mm_mask.nii'), ...
                });

        case 'individual_coords_10mm'
            opt.maskName = horzcat(opt.maskName, ...
                { ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-VWFAfr_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-lLO_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-rLO_radius-10mm_mask.nii'), ...
                });

        case 'individual_coords_8mm'
            opt.maskName = horzcat(opt.maskName, ...
                { ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-VWFAfr_radius-8mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-lLO_radius-8mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-rLO_radius-8mm_mask.nii'), ...
                });

        case 'anatomical_intersection_8mm'
                opt.maskName = horzcat(opt.maskName, ...
                { ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-AnatIntersection_label-VWFAfr_radius-8mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-AnatIntersection_label-lLO_radius-8mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-AnatIntersection_label-rLO_radius-8mm_mask.nii'), ...
                });

        case 'individual_coords_50vx'

            % name contains final voxel size, unpredictable. So go fetch whatever name it has
            vwfafr_str = ['../../outputs/derivatives/cpp_spm-rois/sub-',num2str(subID),'/rsub-',num2str(subID),'_space-MNI_trial-Expansion_label-VWFAfr_voxels-*.nii'];
            vwfafr = dir(vwfafr_str);
%             llo_str = ['../../outputs/derivatives/cpp_spm-rois/sub-',num2str(subID),'/rsub-',num2str(subID),'_space-MNI_trial-Expansion_label-lLO_voxels-*.nii'];
%             llo = dir(llo_str);
%             rlo_str = ['../../outputs/derivatives/cpp_spm-rois/sub-',num2str(subID),'/rsub-',num2str(subID),'_space-MNI_trial-Expansion_label-rLO_voxels-*.nii'];
%             rlo = dir(rlo_str);

            % add the names to the list
            opt.maskName = horzcat(opt.maskName, ...
                { ...
                vwfafr.name, ...
%                 llo.name, ...
%                 rlo.name, ...
                });
    end

    % use in output roi name
    opt.maskLabel = {'VWFAfr', 'lLO', 'rLO'};
end

end
