function [opt] = mvpa_evrel_chooseMask(opt)

opt.maskName = [];

for iSub = 1:numel(opt.subjects)

    subID = opt.subjects{iSub};

    % default one is the old way
    if isempty(opt.roiMethod)
        opt.roiMethod = 'individual_coords_8mm';
    end

    % different subfolders for different methods
    %         opt.maskPath = fullfile(opt.dir.rois, opt.roiMethod);

    % go to maskPath and get all the .nii files


    % based on the method we're using, pick the ROIs
    switch opt.roiMethod
        case 'general_coords_10mm'
            opt.maskName = horzcat(opt.maskName, ...
                { ...
                strcat('sub-', num2str(subID), '_space-MNI_trial-NeurosynthCoords_label-VWFAfr_radius-10mm_mask.nii'), ...
                strcat('sub-', num2str(subID), '_space-MNI_trial-NeurosynthCoords_label-VWFAbr_radius-10mm_mask.nii'), ...
                strcat('sub-', num2str(subID), '_space-MNI_trial-NeurosynthCoords_label-lLO_radius-10mm_mask.nii'), ...
                strcat('sub-', num2str(subID), '_space-MNI_trial-NeurosynthCoords_label-lpFS_radius-10mm_mask.nii'), ...
                strcat('sub-', num2str(subID), '_space-MNI_trial-NeurosynthCoords_label-rLO_radius-10mm_mask.nii'), ...
                strcat('sub-', num2str(subID), '_space-MNI_trial-NeurosynthCoords_label-rpFS_radius-10mm_mask.nii') ...
                });

        case 'individual_coords_marsbar'
            opt.maskName = horzcat(opt.maskName, ...
                { ...
                strcat('rsub-', num2str(subID), '_space-MNI_label-VWFAfr_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_label-VWFAbr_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_label-lLO_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_label-lpFS_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_label-rLO_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_label-rpFS_radius-10mm_mask.nii') ...
                });

        case 'individual_coords_10mm'
            opt.maskName = horzcat(opt.maskName, ...
                { ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-VWFAfr_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-VWFAbr_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-lLO_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-lpFS_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-rLO_radius-10mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-rpFS_radius-10mm_mask.nii') ...
                });

        case 'individual_coords_8mm'
            opt.maskName = horzcat(opt.maskName, ...
                { ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-VWFAfr_radius-8mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-VWFAbr_radius-8mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-lLO_radius-8mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-lpFS_radius-8mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-rLO_radius-8mm_mask.nii'), ...
                strcat('rsub-', num2str(subID), '_space-MNI_trial-IndividualCoords_label-rpFS_radius-8mm_mask.nii') ...
                });

        case 'individual_coords_50vx'

            % name contains final voxel size, unpredictable. So go fetch whatever name it has
            vwfafr_str = ['../../outputs/derivatives/cpp_spm-rois/sub-',num2str(subID),'/rsub-',num2str(subID),'_space-MNI_trial-IndividualCoords_label-VWFAfr_voxels-*.nii'];
            vwfafr = dir(vwfafr_str);
            vwfabr_str = ['../../outputs/derivatives/cpp_spm-rois/sub-',num2str(subID),'/rsub-',num2str(subID),'_space-MNI_trial-IndividualCoords_label-VWFAbr_voxels-*.nii'];
            vwfabr = dir(vwfabr_str);
            llo_str = ['../../outputs/derivatives/cpp_spm-rois/sub-',num2str(subID),'/rsub-',num2str(subID),'_space-MNI_trial-IndividualCoords_label-lLO_voxels-*.nii'];
            llo = dir(llo_str);
            lpfs_str = ['../../outputs/derivatives/cpp_spm-rois/sub-',num2str(subID),'/rsub-',num2str(subID),'_space-MNI_trial-IndividualCoords_label-lpFS_voxels-*.nii'];
            lpfs = dir(lpfs_str);
            rlo_str = ['../../outputs/derivatives/cpp_spm-rois/sub-',num2str(subID),'/rsub-',num2str(subID),'_space-MNI_trial-IndividualCoords_label-rLO_voxels-*.nii'];
            rlo = dir(rlo_str);
            rpfs_str = ['../../outputs/derivatives/cpp_spm-rois/sub-',num2str(subID),'/rsub-',num2str(subID),'_space-MNI_trial-IndividualCoords_label-rpFS_voxels-*.nii'];
            rpfs = dir(rpfs_str);

            % add the names to the list
            opt.maskName = horzcat(opt.maskName, ...
                { ...
                vwfafr.name, ...
                vwfabr.name, ...
                llo.name, ...
                lpfs.name, ...
                rlo.name, ...
                rpfs.name ...
                });
    end

    % use in output roi name
    opt.maskLabel = {'VWFAfr', 'VWFAbr', 'lLO', 'lpFS', 'rLO', 'rpFS'};
end

end
