
clear;
clc;

warning('off');

% add spm to the path
addpath(fullfile(pwd, '..', 'lib', 'bidspm'));
addpath(fullfile(pwd, '..', 'lib', 'CPP_BIDS'));
bidspm;

% check inside if everything is ok before starting the pipeline
opt = stats_blockMvpa_option();


%% New command to do everything

bidspm(opt.dir.input, opt.dir.output, 'subject', ...
            'action', 'stats', ...
            'preproc_dir', opt.dir.preproc, ...        % specific to stats
            'model_file', opt.model.file, ...          % specific to stats
            'participant_label', {'012'}, ...
            'dry_run', false, ...
            'bids_filter_file', struct([]), ...
            'boilerplate_only', false, ...
            'verbosity', 2, ...
            'space', {'individual', 'IXI549Space'}, ...
            'options', struct([]), ...,
            'roi_based', false, ...
            'design_only', false, ...
            'ignore', {}, ...
            'concatenate', true, ...
            'task', {'wordsDecoding'}, ...
            'fwhm', 2, ...
            'skip_validation', true)
 